/* Allegro datafile object indexes, produced by dat v4.4.3, Unix */
/* Datafile: datos.dat */
/* Date: Mon Aug 31 22:31:52 2026 */
/* Do not hand edit! */

#define ARROW_GETIN_BMP                  0        /* BMP  */
#define BG0_TMX                          1        /* DATA */
#define BG1_SHOP2_BMP                    2        /* BMP  */
#define BG1_SHOP_TMX                     3        /* DATA */
#define BG1_TMX                          4        /* DATA */
#define BG2_SHOP_TMX                     5        /* DATA */
#define BG2_TMX                          6        /* DATA */
#define BG3_TMX                          7        /* DATA */
#define BG4_TMX                          8        /* DATA */
#define BG5_TMX                          9        /* DATA */
#define BG6_TMX                          10       /* DATA */
#define BIG_SPRITESHEET_BMP              11       /* BMP  */
#define BIRD_SPRITESHEET_BMP             12       /* BMP  */
#define BOMB_SPRITESHEET_BMP             13       /* BMP  */
#define BOOK_BMP                         14       /* BMP  */
#define BRUNO_SPRITESHEET_BMP            15       /* BMP  */
#define BULLET_BMP                       16       /* BMP  */
#define COCHE_SPRITESHEET_BMP            17       /* BMP  */
#define CONTINUE_TMX                     18       /* DATA */
#define DOG_SPRITESHEET_BMP              19       /* BMP  */
#define END_LEVEL_BMP                    20       /* BMP  */
#define FAROLA_BMP                       21       /* BMP  */
#define FONT_FNT                         22       /* FONT */
#define GUARD_SPRITESHEET_BMP            23       /* BMP  */
#define HEAD_BMP                         24       /* BMP  */
#define INTRO_MID                        25       /* MIDI */
#define JERINGA_BMP                      26       /* BMP  */
#define JORDI_LOGO_BMP                   27       /* BMP  */
#define JOVEN_SPRITESHEET_BMP            28       /* BMP  */
#define LEVEL2_INTRO_BMP                 29       /* BMP  */
#define LEVEL3_INTRO2_BMP                30       /* BMP  */
#define LEVEL3_INTRO3_BMP                31       /* BMP  */
#define LEVEL4_CRASH_BMP                 32       /* BMP  */
#define LEVEL4_INTRO_BMP                 33       /* BMP  */
#define LEVEL5_INTRO_BMP                 34       /* BMP  */
#define LEVEL7_INTRO_BMP                 35       /* BMP  */
#define LIFEBAR_BMP                      36       /* BMP  */
#define LIFEBAR_BRUNO_BMP                37       /* BMP  */
#define LIFEBAR_ENEMY_BMP                38       /* BMP  */
#define LIFEBAR_MARTIN_BMP               39       /* BMP  */
#define LIFEBAR_THROWABLE_BMP            40       /* BMP  */
#define MARTIN_SPRITESHEET_BMP           41       /* BMP  */
#define MENU2_BMP                        42       /* BMP  */
#define MICROPHONE_BMP                   43       /* BMP  */
#define MINICAR_BMP                      44       /* BMP  */
#define MONEY_BMP                        45       /* BMP  */
#define MSDOS_MID                        46       /* MIDI */
#define MSDOSCLUB_BMP                    47       /* BMP  */
#define PALETE_INTRO_BMP                 48       /* PAL  */
#define PALETE_JORDI_LOGO_BMP            49       /* PAL  */
#define PCONDENSER_BMP                   50       /* BMP  */
#define PELOBROCOLI_SPRITESHEET_BMP      51       /* BMP  */
#define PFLOW_BMP                        52       /* BMP  */
#define PFUEL_BMP                        53       /* BMP  */
#define PIELDETORO_INTRO3_BMP            54       /* BMP  */
#define PLATAFORMA2_BMP                  55       /* BMP  */
#define PLATAFORMA_BMP                   56       /* BMP  */
#define SINKING1_BMP                     57       /* BMP  */
#define SINKING2_BMP                     58       /* BMP  */
#define TEXT_MENU_BMP                    59       /* BMP  */
#define TILES_BMP                        60       /* BMP  */
#define TNT_BMP                          61       /* BMP  */
#define USHANKA_BMP                      62       /* BMP  */

