/* Allegro datafile object indexes, produced by dat v4.4.3, Unix */
/* Datafile: datos.dat */
/* Date: Thu Aug 20 21:30:05 2026 */
/* Do not hand edit! */

#define ARROW_GETIN_BMP                  0        /* BMP  */
#define BG0_TMX                          1        /* DATA */
#define BG1_SHOP2_BMP                    2        /* BMP  */
#define BG1_SHOP_TMX                     3        /* DATA */
#define BG1_TMX                          4        /* DATA */
#define BG2_SHOP_TMX                     5        /* DATA */
#define BG2_TMX                          6        /* DATA */
#define BG3_TMX                          7        /* DATA */
#define BG4_TMX                          8        /* DATA */
#define BIRD_SPRITESHEET_BMP             9        /* BMP  */
#define BOMB_SPRITESHEET_BMP             10       /* BMP  */
#define BOOK_BMP                         11       /* BMP  */
#define BRUNO_SPRITESHEET_BMP            12       /* BMP  */
#define COCHE_SPRITESHEET_BMP            13       /* BMP  */
#define CONTINUE_TMX                     14       /* DATA */
#define DOG_SPRITESHEET_BMP              15       /* BMP  */
#define FAROLA_BMP                       16       /* BMP  */
#define FONT_FNT                         17       /* FONT */
#define HEAD_BMP                         18       /* BMP  */
#define INTRO_MID                        19       /* MIDI */
#define JERINGA_BMP                      20       /* BMP  */
#define JORDI_LOGO_BMP                   21       /* BMP  */
#define JOVEN_SPRITESHEET_BMP            22       /* BMP  */
#define LEVEL2_INTRO_BMP                 23       /* BMP  */
#define LEVEL3_INTRO2_BMP                24       /* BMP  */
#define LEVEL3_INTRO3_BMP                25       /* BMP  */
#define LEVEL4_CRASH_BMP                 26       /* BMP  */
#define LEVEL4_INTRO_BMP                 27       /* BMP  */
#define LIFEBAR_BMP                      28       /* BMP  */
#define LIFEBAR_BRUNO_BMP                29       /* BMP  */
#define LIFEBAR_ENEMY_BMP                30       /* BMP  */
#define LIFEBAR_MARTIN_BMP               31       /* BMP  */
#define LIFEBAR_THROWABLE_BMP            32       /* BMP  */
#define MARTIN_SPRITESHEET_BMP           33       /* BMP  */
#define MENU2_BMP                        34       /* BMP  */
#define MICROPHONE_BMP                   35       /* BMP  */
#define MINICAR_BMP                      36       /* BMP  */
#define MONEY_BMP                        37       /* BMP  */
#define MSDOS_MID                        38       /* MIDI */
#define MSDOSCLUB_BMP                    39       /* BMP  */
#define PALETE_INTRO_BMP                 40       /* PAL  */
#define PALETE_JORDI_LOGO_BMP            41       /* PAL  */
#define PCONDENSER_BMP                   42       /* BMP  */
#define PFLOW_BMP                        43       /* BMP  */
#define PFUEL_BMP                        44       /* BMP  */
#define PIELDETORO_INTRO3_BMP            45       /* BMP  */
#define PLATAFORMA2_BMP                  46       /* BMP  */
#define PLATAFORMA_BMP                   47       /* BMP  */
#define SINKING1_BMP                     48       /* BMP  */
#define SINKING2_BMP                     49       /* BMP  */
#define TEXT_MENU_BMP                    50       /* BMP  */
#define TILES_BMP                        51       /* BMP  */
#define USHANKA_BMP                      52       /* BMP  */

