/* Allegro datafile object indexes, produced by dat v4.4.3, Unix */
/* Datafile: datos.dat */
/* Date: Mon Sep  7 17:42:49 2026 */
/* Do not hand edit! */

#define ARROW_GETIN_BMP                  0        /* BMP  */
#define BG0_TMX                          1        /* DATA */
#define BG1_SHOP2_BMP                    2        /* BMP  */
#define BG1_SHOP_TMX                     3        /* DATA */
#define BG1_TMX                          4        /* DATA */
#define BG2_SHOP_TMX                     5        /* DATA */
#define BG2_TMX                          6        /* DATA */
#define BG3_TMX                          7        /* DATA */
#define BG4_TMX                          8        /* DATA */
#define BG5_TMX                          9        /* DATA */
#define BG6_TMX                          10       /* DATA */
#define BIG_SPRITESHEET_BMP              11       /* BMP  */
#define BIRD_SPRITESHEET_BMP             12       /* BMP  */
#define BOMB_SPRITESHEET_BMP             13       /* BMP  */
#define BOOK_BMP                         14       /* BMP  */
#define BRUNO_SPRITESHEET_BMP            15       /* BMP  */
#define BULLET_BMP                       16       /* BMP  */
#define CARS_BMP                         17       /* BMP  */
#define COCHE_SPRITESHEET_BMP            18       /* BMP  */
#define CONTINUE_TMX                     19       /* DATA */
#define DIARIO_BMP                       20       /* BMP  */
#define DOG_SPRITESHEET_BMP              21       /* BMP  */
#define END_LEVEL_BMP                    22       /* BMP  */
#define FAROLA_BMP                       23       /* BMP  */
#define FINAL_MID                        24       /* MIDI */
#define FONT_FNT                         25       /* FONT */
#define GIRL_FLI                         26       /* FLIC */
#define GUARD_SPRITESHEET_BMP            27       /* BMP  */
#define HEAD_BMP                         28       /* BMP  */
#define INTER_MID                        29       /* MIDI */
#define INTRO_MID                        30       /* MIDI */
#define JERINGA_BMP                      31       /* BMP  */
#define JORDI_LOGO_BMP                   32       /* BMP  */
#define JOVEN_SPRITESHEET_BMP            33       /* BMP  */
#define LEVEL1_FUNKY_MID                 34       /* MIDI */
#define LEVEL2_INTRO_BMP                 35       /* BMP  */
#define LEVEL2_POLICIACO_MID             36       /* MIDI */
#define LEVEL3_INTRO2_BMP                37       /* BMP  */
#define LEVEL3_INTRO3_BMP                38       /* BMP  */
#define LEVEL3_MID                       39       /* MIDI */
#define LEVEL4_CRASH_BMP                 40       /* BMP  */
#define LEVEL4_DETECTIVE_MID             41       /* MIDI */
#define LEVEL4_INTRO_BMP                 42       /* BMP  */
#define LEVEL5_INTRO_BMP                 43       /* BMP  */
#define LEVEL5_MID                       44       /* MIDI */
#define LEVEL6_MID                       45       /* MIDI */
#define LEVEL7_INTRO_BMP                 46       /* BMP  */
#define LIFEBAR_BMP                      47       /* BMP  */
#define LIFEBAR_BRUNO_BMP                48       /* BMP  */
#define LIFEBAR_ENEMY_BMP                49       /* BMP  */
#define LIFEBAR_MARTIN_BMP               50       /* BMP  */
#define LIFEBAR_THROWABLE_BMP            51       /* BMP  */
#define MARTIN_SPRITESHEET_BMP           52       /* BMP  */
#define MENU2_BMP                        53       /* BMP  */
#define MICROPHONE_BMP                   54       /* BMP  */
#define MINICAR_BMP                      55       /* BMP  */
#define MONEY_BMP                        56       /* BMP  */
#define MSDOS_MID                        57       /* MIDI */
#define MSDOSCLUB_BMP                    58       /* BMP  */
#define PALETE_INTRO_BMP                 59       /* PAL  */
#define PALETE_JORDI_LOGO_BMP            60       /* PAL  */
#define PCONDENSER_BMP                   61       /* BMP  */
#define PELOBROCOLI_SPRITESHEET_BMP      62       /* BMP  */
#define PFLOW_BMP                        63       /* BMP  */
#define PFUEL_BMP                        64       /* BMP  */
#define PIELDETORO_INTRO3_BMP            65       /* BMP  */
#define PLATAFORMA2_BMP                  66       /* BMP  */
#define PLATAFORMA_BMP                   67       /* BMP  */
#define SINKING1_BMP                     68       /* BMP  */
#define SINKING2_BMP                     69       /* BMP  */
#define TEXT_MENU_BMP                    70       /* BMP  */
#define TILES_BMP                        71       /* BMP  */
#define TNT_BMP                          72       /* BMP  */
#define USHANKA_BMP                      73       /* BMP  */
#define WAVE_BULLET_BMP                  74       /* BMP  */
#define WON_MID                          75       /* MIDI */

